### ISSUE TITLE
Support Multiple ICAT Domains on Same Instance of GlassFish

### ISSUE THREAD

**Issue by PeterParker** [icatproject-contrib/puppet-icat#3]
Looks like we are heading towards having (at least) two ICAT instances at ORNL -- one for SNS and one for HFIR, so this needs to be supported by the module as it is not currently.

First places to look are how the GlassFish module we use handles assigning ports, and also we need to pass unique names to each of the GlassFish domains that would be created.

**Comment by tomgriffinstfc** [comment]
I may have misunderstood, but if you are using two ICATs for separation and to allow independent maintenance, then I would recommend running them on different glassfish servers, or you still have a common maintenance time problem.

**Comment by PeterParker** [comment]
Nope, you didn't misunderstand.  Thanks for the recommendation.

In our case we would still have a common maintenance time problem as far as our _databases_ are concerned, but we're still going to go ahead and have separate instances as you suggest since it would be worth while to be able to upgrade or even just restart GlassFish independently.
